Repository vincentliu104/Learning-Together, pull requests merged in 2018-07, with the labels that each got.

#2 update Readme.md
  README.md
Labels: test

#5 add Cheat Sheet
  resources/markdown.md
Labels: good first issue

#6 add git and vscode learning resources
  resources/Git/README.md
  resources/VSCode/README.md
Labels: enhancement

#8 新增ES6·Webpack·React資料夾
  resources/ES6/README.md
  resources/React/README.md
  resources/Webpack/README.md
Labels: knowledge

#12 Vincent/markdown
  resources/.gitkeep
  resources/Webpack/.gitkeep
  resources/markdown.md
Labels: knowledge

#17 Da/resources
  resources/React/package.json
Labels: learning
